<a href="https://colab.research.google.com/github/michalis0/Business-Intelligence-and-Analytics/blob/master/labs/03%20-%20Pandas%20and%20Python/exercises/exercise_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

In [1]:
import pandas as pd

## Question 1

 In the API walkthrough, we show you how to retrieve data from a website by making a request. For this exercise, we've already crawled the data and combined it into a dataset that includes a list of movies along with their IMDB ratings and other metadata.

You can load the data from the this URL: "https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/refs/heads/master/data/imdb_movies.csv"

In [11]:
dataset_movies = pd.read_csv('https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/refs/heads/master/data/imdb_movies.csv')
dataset_movies.head()

,Title,Year,Genres,Duration,Rating,MPA,Votes
0,1. American Sniper,2014,"['Action', 'Biography', 'Drama', 'War']",2h 13m,7.3,R,543K
1,2. The Hunger Games: Mockingjay - Part 1,2014,"['Dystopian Sci-Fi', 'Action', 'Adventure', 'S...",2h 3m,6.6,PG-13,517K
2,3. Guardians of the Galaxy,2014,"['Quest', 'Space Sci-Fi', 'Superhero', 'Action...",2h 1m,8.0,PG-13,1.3M
3,4. Captain America: The Winter Soldier,2014,"['Conspiracy Thriller', 'Political Thriller', ...",2h 16m,7.7,PG-13,920K
4,5. The Lego Movie,2014,"['Computer Animation', 'Dystopian Sci-Fi', 'Gl...",1h 40m,7.7,PG,397K

## Question 2

Check the data by using the following functions:
* `.head(n)`(print the first n rows, `head()` by default returns the first 5 rows)
* `.tail(n)` (print the last n rows, `.tail()` by default returns the last 5 rows)
* `.columns` (column names)
* `.index` (raw identifier)
* `.dtypes` (column types)

In [12]:
# Beginning of the list
dataset_movies.head(100)

,Title,Year,Genres,Duration,Rating,MPA,Votes
0,1. American Sniper,2014,"['Action', 'Biography', 'Drama', 'War']",2h 13m,7.3,R,543K
1,2. The Hunger Games: Mockingjay - Part 1,2014,"['Dystopian Sci-Fi', 'Action', 'Adventure', 'S...",2h 3m,6.6,PG-13,517K
2,3. Guardians of the Galaxy,2014,"['Quest', 'Space Sci-Fi', 'Superhero', 'Action...",2h 1m,8.0,PG-13,1.3M
3,4. Captain America: The Winter Soldier,2014,"['Conspiracy Thriller', 'Political Thriller', ...",2h 16m,7.7,PG-13,920K
4,5. The Lego Movie,2014,"['Computer Animation', 'Dystopian Sci-Fi', 'Gl...",1h 40m,7.7,PG,397K
...,...,...,...,...,...,...,...
95,96. 3 Days to Kill,2014,"['Dark Comedy', 'Spy', 'Action', 'Drama', 'Thr...",1h 57m,6.2,PG-13,99K
96,97. Deliver Us from Evil,2014,"['True Crime', 'Crime', 'Horror', 'Mystery', '...",1h 58m,6.2,R,88K
97,98. When the Game Stands Tall,2014,"['Football', 'Biography', 'Drama', 'Family', '...",1h 55m,6.6,PG,17K
98,99. Draft Day,2014,"['Football', 'Drama', 'Sport']",1h 50m,6.8,PG-13,69K
99,100. The Best of Me,2014,"['Teen Romance', 'Tragedy', 'Tragic Romance', ...",1h 58m,6.7,PG-13,79K

In [14]:
# End of the list
dataset_movies.tail(2)

,Title,Year,Genres,Duration,Rating,MPA,Votes
5948,599. Fight or Flight,2024,"['Action', 'Comedy']",2h 46m,7.0,NaN,117
5949,600. A Sacrifice,2024,"['Drama', 'Horror', 'Mystery', 'Thriller']",1h 34m,5.1,R,4.3K

In [13]:
# Column names
dataset_movies.columns

Index(['Title', 'Year', 'Genres', 'Duration', 'Rating', 'MPA', 'Votes'], dtype='object')

In [15]:
# Raw identifier
dataset_movies.index

RangeIndex(start=0, stop=5950, step=1)

In [16]:
# Column types
dataset_movies.dtypes

Title       object
Year         int64
Genres      object
Duration    object
Rating      object
MPA         object
Votes       object
dtype: object

## Question 3

Remember that each column/attribute of our data may have different attribute types. Have a look at the following table to recall the different DataTypes in Pandas and Python (it is the same as in the walkthrough).

| Pandas dtype  | Python type  | NumPy type|Usage
| :--- | :--- | :--- | :--- |
| object| str or mixed | string_, unicode_, mixed types| Text or mixed numeric and non_numeric values |
| int 64| int| int_, int8, int16, int32, int64, uint8, uint18, uint32, uint64 | Integer numbers i.e. [1,2,3,...] |
| float64| float| float_, float15, float32, float64 | Floating point numbers (They contain decimal points) |
| bool| bool|bool_| True/False values|
| datetime64 | NA | datetime64[ns]     | Date and time values  |
| timedelta[ns] | NA  | NA| Differences between two datetime|
| category | NA| NA| Finite list of text values|

Use the following cells to convert each column to the required dtype:

In [ ]:
# Convert MPA to category
'''YOUR CODE HERE'''

In [ ]:
# Convert Rating to numeric
'''YOUR CODE HERE'''

Now lets have a look at the new column types:

In [ ]:
# New column types
'''YOUR CODE HERE'''

# Part 2

## Question 4
The dataset contains some null values. Count the number of null values in each column using `.isnull().sum()`.

Then, remove all rows that contain **at least** one null value using `.dropna()`.

Print the shape of the dataframe before and after the cleaning process using `.shape`. How many rows were deleted?


#### Key Parameters for `.dropna()`:

- **axis**:
  - `0` (default) → Drops rows with NaN values.
  - `1` → Drops columns with NaN values.

- **how**:
  - `"any"` (default) → Drops a row if **any** value in the row is NaN.
  - `"all"` → Drops a row only if **all** values in the row are NaN.

- **inplace**:
  - `False` (default) → Returns a new DataFrame with NaN rows removed.
  - `True` → Modifies the original DataFrame in place.

**Solution:**

In [ ]:
# Original shape
'''YOUR CODE HERE'''

In [ ]:
# Get the original number of rows
'''YOUR CODE HERE'''

In [ ]:
# Count the number of null values in each column
'''YOUR CODE HERE'''

In [ ]:
# Drop rows with null values
'''YOUR CODE HERE'''

In [ ]:
# Print shape of data after dropping null values
'''YOUR CODE HERE'''

In [ ]:
# Check the number of rows after dropping
'''YOUR CODE HERE'''

<h2>Important: This question answers the Moodle quiz question 1. </h2>

In [ ]:
# Print the percentage of rows removed from the dataset as a result of the cleaning
'''YOUR CODE HERE'''

## Question 5

We will now apply some selections/filters on the dataframe to get some insights:
- Display the statistics of the ratings (hint: use `describe()`).
- Find the average rating of movies per year (hint: use `groupby()` and `mean()`).
- Print the top 10 movies with lowest ratings in 2022 (hint: filter movies that released in 2022 and use `sort_values()`).
- [Optional] Find the average rating of action movies per year (hint: filter movies that contain 'Action' in their Genres, use `groupby()` and `mean()`).

**Solution**:

In [ ]:
# Display the statistics of the ratings
'''YOUR CODE HERE'''

In [ ]:
# Average rating per year
'''YOUR CODE HERE'''

<h2> Important: This question answers the Moodle quiz question 2. <h2>

In [ ]:
# Top 10 movies with the lowest rating in 2022
'''YOUR CODE HERE'''

In [ ]:
# Average rating of action movies per year
# Filter movies which Genres list contains 'Action'
'''YOUR CODE HERE'''

# Group by year and calculate the average rating
'''YOUR CODE HERE'''